version: '3.7'
services:
  fe:
    image: untadee/comment-survey-fe-4:latest
    networks:
      - traefik-public
    environment:
      - VUE_APP_API_URL=https://rais4.dista.uninsubria.it/comment-api
    deploy:
      # service resource management
      # resources:
        # Hard limit - Docker does not allow to allocate more
        # limits:
        #   cpus: '0.50'
        #   memory: 512M
        # Soft limit - Docker makes best effort to return to it
        # reservations:
        #   cpus: '0.50'
        #   memory: 256M
      # service restart policy
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.comment-survey-fe-4.rule=Host(`rais4.dista.uninsubria.it`)
        - traefik.http.routers.comment-survey-fe-4.entrypoints=http
        - traefik.http.routers.comment-survey-fe-4.middlewares=https-redirect
        - traefik.http.routers.comment-survey-fe-4.entrypoints=https
        - traefik.http.routers.comment-survey-fe-4.tls=true
        - traefik.http.services.comment-survey-fe-4.loadbalancer.server.port=3000

        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true

        - traefik.http.routers.comment-survey-fe-4.tls.certresolver=le

  be:
    image: untadee/comment-survey-be-4:latest
    networks:
      - mongodb_net
      - traefik-public
    environment:
      - MONGODB_URL=mongodb://admin:123123@mongodb_container:27017/comment-survey?authSource=admin
    deploy:
      labels:
        # Frontend
        - "traefik.enable=true"
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - "traefik.http.routers.comment-survey-be-4.rule=Host(`rais4.dista.uninsubria.it`) && PathPrefix(`/comment-api/`)"
        - "traefik.http.routers.comment-survey-be-4.entrypoints=https"
        - traefik.http.routers.comment-survey-be-4.tls=true
        - "traefik.http.services.comment-survey-be-4.loadbalancer.server.port=3333"
        - "traefik.http.routers.comment-survey-be-4.service=comment-survey-be-4"
        - traefik.http.routers.comment-survey-be-4.middlewares=comment-survey-strip-prefix-4
        - traefik.http.middlewares.comment-survey-strip-prefix-4.stripprefix.prefixes=/comment-api
networks:
  traefik-public:
    external: true
  mongodb_net:
    external: true
volumes:
  data:


